# Generated by Django 2.2.3 on 2019-07-17 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AD_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expired_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 18, 17, 7, 42, 48773))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
