# Generated by Django 2.2.3 on 2019-07-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_token', '0003_auto_20190717_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_token',
            name='expired_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
